import os
OPENWEATHER_API_KEY = os.getenv('OPENWEATHER_API_KEY')
WAQI_API_KEY = os.getenv('WAQI_API_KEY')
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')
FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID')
